### ISSUE TITLE
no connection.php

### ISSUE THREAD

**Issue by kakakolaka** [sdg12321/Website-For-K4-System-And-CS2-SimpleAdmin#2]
no connection.php

**Comment by sdg12321** [comment]
https://github.com/sdg12321/Website-For-K4-System-And-CS2-SimpleAdmin?tab=readme-ov-file#installation

You just need to unzip the archives for the plugin you want to use on the website, and the connection files for each plugin will appear in src/. Read the installation instructions. For additional help, you can find me on Discord; channel id is on the main page.

**Comment by kakakolaka** [comment]
got it,  i was using version 2.0 which was using connection.php instead of those 2 file, thanks

**Comment by sdg12321** [comment]
I understand. I've made numerous changes from version 2 until now, ranging from connecting multiple servers to implementing the admin plugin. It was challenging for me to maintain the same structure, but now I've brought it to a stable stage, and I hope the structure will remain the same in the future. You can contact me on Discord anytime for any suggestions or assistance.
