### ISSUE TITLE
rank list

### ISSUE THREAD

**Issue by asdfxD** [sdg12321/Website-For-K4-System-And-CS2-SimpleAdmin#4]
the rank list does not show any players, only the time list works.

![rankslist](https://github.com/sdg12321/Website-For-K4-System-And-CS2-SimpleAdmin/assets/24253340/03d8cfbf-fb8f-43bf-9d0a-90071d4140fb)

**Comment by sdg12321** [comment]
I know, the k4-system plugin was updated. I will update the website in next 3 days.

**Comment by sdg12321** [comment]
The pages have been updated; please download version 5.1.0.
